# Generated by Django 5.2.6 on 2025-10-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_sent_at', models.DateTimeField(auto_now_add=True)),
                ('days_before_expiry', models.PositiveIntegerField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('alert_type', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard'), ('sms', 'SMS')], default='email', max_length=20)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='donations.donation')),
            ],
            options={
                'ordering': ['-alert_sent_at'],
                'unique_together': {('donation', 'days_before_expiry', 'recipient_email')},
            },
        ),
    ]
