# Generated by Django 5.2.6 on 2025-11-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, help_text='Image is required for new donations', null=True, upload_to='donations/'),
        ),
    ]
