# Generated by Django 5.2.6 on 2025-11-21 16:36

from django.db import migrations


def set_all_donations_to_pending(apps, schema_editor):
    """Set all existing donations to PENDING approval status"""
    Donation = apps.get_model('donations', 'Donation')
    # Update all donations to pending
    Donation.objects.all().update(approval_status='pending')


def reverse_migration(apps, schema_editor):
    """Reverse by setting all back to approved"""
    Donation = apps.get_model('donations', 'Donation')
    Donation.objects.all().update(approval_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_approval_status_donation_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RunPython(set_all_donations_to_pending, reverse_migration),
    ]
