# Generated by Django 5.2.6 on 2025-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
