# Generated by Django 5.2.6 on 2025-11-21 16:37

from django.db import migrations


def set_all_requests_to_pending(apps, schema_editor):
    """Set all existing medicine requests to PENDING approval status"""
    MedicineRequest = apps.get_model('requests', 'MedicineRequest')
    # Update all requests to pending
    MedicineRequest.objects.all().update(approval_status='pending')


def reverse_migration(apps, schema_editor):
    """Reverse by setting all back to approved"""
    MedicineRequest = apps.get_model('requests', 'MedicineRequest')
    MedicineRequest.objects.all().update(approval_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_medicinerequest_approval_status_and_more'),
    ]

    operations = [
        migrations.RunPython(set_all_requests_to_pending, reverse_migration),
    ]
