# Generated by Django 5.2.6 on 2025-09-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('uses', models.CharField(blank=True, max_length=255)),
                ('form', models.CharField(blank=True, max_length=60)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
