# Generated by Django 5.2.6 on 2025-10-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_sent_at', models.DateTimeField(auto_now_add=True)),
                ('days_before_expiry', models.PositiveIntegerField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='healthbridge_app.donation')),
            ],
            options={
                'unique_together': {('donation', 'days_before_expiry', 'recipient_email')},
            },
        ),
    ]
