# Generated by Django 5.2.6 on 2025-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0002_donation_genericmedicine_brandmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_images/'),
        ),
    ]
