# Generated by Django 5.2.6 on 2025-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0002_expiryalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiryalert',
            options={'ordering': ['-alert_sent_at']},
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='alert_type',
            field=models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard'), ('sms', 'SMS')], default='email', max_length=20),
        ),
    ]
