# Generated by Django 5.2.6 on 2025-10-15 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0003_alter_expiryalert_options_expiryalert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('quantity_needed', models.PositiveIntegerField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Why do you need this medicine?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('matched_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='healthbridge_app.donation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
