# Generated by Django 5.2.6 on 2025-10-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0003_donation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
    ]
