# Generated by Django 5.2.6 on 2025-10-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0004_remove_donation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
