# Generated by Django 5.2.6 on 2025-10-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0005_sync_with_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='medicinerequest',
            name='matched_donation',
        ),
        migrations.RemoveField(
            model_name='medicinerequest',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='ExpiryAlert',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='MedicineRequest',
        ),
    ]
