# Generated by Django 5.2.6 on 2025-11-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0006_remove_donation_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_selected',
            field=models.BooleanField(default=False, help_text='Has the user completed their one-time role selection?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('recipient', 'Recipient')], help_text='User role: Donor or Recipient (permanent after selection)', max_length=10, null=True),
        ),
    ]
