# Generated by Django 5.2.6 on 2025-11-21 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthbridge_app', '0007_customuser_role_selected_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('donation_approved', 'Donation Approved'), ('donation_rejected', 'Donation Rejected'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_matched', 'Request Matched'), ('medicine_expiring', 'Medicine Expiring Soon'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('donation_id', models.IntegerField(blank=True, null=True)),
                ('request_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='healthbridg_user_id_80d4d1_idx'), models.Index(fields=['user', 'is_read'], name='healthbridg_user_id_c15232_idx')],
            },
        ),
    ]
